In [11]:
l = [1,2,3,4,5]

In [12]:
print(l)

[1, 2, 3, 4, 5]


In [13]:
l = ['Python', 'Java', 'C++', 'C#', 1,2,3]

In [14]:
l

['Python', 'Java', 'C++', 'C#', 1, 2, 3]

In [15]:
import array as arr

In [17]:
a = arr.array('i', [1,2,3,4,5])

In [18]:
a

array('i', [1, 2, 3, 4, 5])

In [19]:
b = arr.array('i', [1,2,3,'Python'])

TypeError: 'str' object cannot be interpreted as an integer

In [20]:
import numpy as np

In [21]:
arr = np.array([1,2,3,4,5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
print(arr * 2)

[ 2  4  6  8 10]


In [24]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [25]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [27]:
for row in matrix:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [28]:
for i in range(3):
    for j in range(3):
        print(matrix[i][j])

1
2
3
4
5
6
7
8
9
